### ISSUE TITLE
Crash on leaving Torture Chambers area

### ISSUE THREAD

**Issue by epengr** [dghost/quake2vr#19]
Every time, can not play past this point.   Is it just me?

The level loading bar doesn't move at all, it you click or hit any key the screen fades and windows "This program has stopped working" dialog appears.

Windows 8.1, evga GTX 770 SC, DK2, all drivers up to date.

**Comment by mscoder610** [comment]
Can't reproduce this in v2.0.0a. (I started directly at Torture Chambers via 'map jail4', went all the way through the level, followed the exit to the Security Complex (jail3), and went through the loading screen fine.
