### ISSUE TITLE
Issues with both v1.9.3 and v1.3.1

### ISSUE THREAD

**Issue by turbolego** [dghost/quake2vr#30]
v1.3.1: no issues other than it plays in windowed mode, and adding custom resolution to config does nothing.

v1.9.3: not sure... i get this weird screen error:

![photo](https://cloud.githubusercontent.com/assets/2650749/7072647/44b6ec28-deee-11e4-8d68-5009f81c29e5.png)

My setup: DK2 running v. 1.6 (SDK 0.5.0.1) in extended mode without dk1 legacy app support.
Windows 8.1 64-bit, 860M GTX gpu, i7 cpu.

Looks cool tho, wish i could play. :P

**Comment by dghost** [comment]
HUH. That's definitely abnormal. I suspect I know what's going on, but sadly am not gonna get a chance to do much about it until either this weekend or next. I'll look into it and update this when I have a fix, though.

**Comment by turbolego** [comment]
No problem man, no rush.
Just post back here if you need more information etc.

Peace.:smiley:
