### ISSUE TITLE
Running with Vridge.

### ISSUE THREAD

**Issue by denzmilk** [dghost/quake2vr#32]
At the moment, I'm unable to get this running with Riftcat Vridge.

Vridge emulates an Oculus SDK 0.6-0.8 HMD. I was wondering if there is any way I might be able to get this running. I've emailed Vridge and they advised that this has been developed for an earlier Oculus version.

I understand there could be a bit of work involved in getting this to run, I would be more than happy to have a go figuring it out myself if I know where to start.

Any help is much appreciated.

**Comment by mscoder610** [comment]
You might try this again with the new v2.0.0a release. The Vridge docs say that Oculus games targetting newer SDKs versions may work if used in conjunction with Revive (since it supports SteamVR), so it might work that way.
