### ISSUE TITLE
crash on entering map power2

### ISSUE THREAD

**Issue by lastsid** [dghost/quake2vr#38]
Every time on entering map power2 througth game or througth console ("map power2") game crashes with message "virtualalloc commit failed".

**Comment by JigenD** [comment]
Getting the same crash and error message upon loading The Reactor map on version 2.0.0

**Comment by jyoung0145** [comment]
I’m having the same problem with loading the Reator map also know as power2.bap

**Comment by jyoung0145** [comment]
I’m having the same problem with the reactor map aka power2 v2.0.0
