### ISSUE TITLE
Stuck on "The End" after completing map "installation"

### ISSUE THREAD

**Issue by Roxra** [dghost/quake2vr#39]
All I can see are the words "The End", I assume it should then take me to the next level but no dice. Buttons don't do anything, can't progress. I think it might be crashing, not sure. Hope you can fix it because I've been loving this mod so far.

**Comment by FolkSong** [comment]
Same problem here.

**Comment by FolkSong** [comment]
I had this but I realized at some point I had copied the shareware pak0 over the full one. Once I switched it back I still got the crash, but I just used the console command "map bunk1" to go to the next level. Then I used some other commands to give me back the weapons I had before.
