### ISSUE TITLE
Request: revise the engine to support RTX

### ISSUE THREAD

**Issue by gusmanb** [dghost/quake2vr#42]
Nvidia is preparing a free version of Quake II with RTX, SLI support and a ton of features, it looks AMAZING. I would beg if you could check if the changes could be applied to the VR version, the code will be publicly available in one month.

Here is more info. https://www.pcgamesn.com/nvidia/quake-ii-rtx-nvidia-ray-tracing

**Comment by mcgrog** [comment]
Bump, Best Idea Ever.

**Comment by sycspysycspy** [comment]
No, you will need a nasa computer to run it at full resolution for VR.

**Comment by gusmanb** [comment]
> 
> 
> No, you will need a nasa computer to run it at full resolution for VR.

Not at all, I can run the RTX version at 4k 90fps, that's enough for two 1080x1200 screens.

**Comment by mcgrog** [comment]
https://github.com/NVIDIA/Q2RTX

**Comment by motorsep** [comment]
Even just pulling RTX shadows would be a good thing for VR.

**Comment by sycspysycspy** [comment]
> 
> 
> > No, you will need a nasa computer to run it at full resolution for VR.
> 
> Not at all, I can run the RTX version at 4k 90fps, that's enough for two 1080x1200 screens.

What is your spec? I have a 1070, running the game with global illumination set to low, at 1600*900 50% resolution(800*450). Can not get a stable 60 fps. Maybe you have a 2080ti, but that is too expensive for most of the gamers.

**Comment by mcgrog** [comment]
> > > No, you will need a nasa computer to run it at full resolution for VR.
> > 
> > 
> > Not at all, I can run the RTX version at 4k 90fps, that's enough for two 1080x1200 screens.
> 
> What is your spec? I have a 1070, running the game with global illumination set to low, at 1600_900 50% resolution(800_450). Can not get a stable 60 fps. Maybe you have a 2080ti, but that is too expensive for most of the gamers.

Theres your problem, Solution - RTX.
Among other things theyre built for handling ray tracing in card.

**Comment by sycspysycspy** [comment]
> 
> 
> > > > No, you will need a nasa computer to run it at full resolution for VR.
> > > 
> > > 
> > > Not at all, I can run the RTX version at 4k 90fps, that's enough for two 1080x1200 screens.
> > 
> > 
> > What is your spec? I have a 1070, running the game with global illumination set to low, at 1600_900 50% resolution(800_450). Can not get a stable 60 fps. Maybe you have a 2080ti, but that is too expensive for most of the gamers.
> 
> Theres your problem, Solution - RTX.
> Among other things theyre built for handling ray tracing in card.

No, you don't get the point, sure my pc is under the spec, but based on steam reviews even some 2080ti owners suffer the "performance problems" such as this one:
"
>Buys $1,000+ 2080 Ti
>Buys $1,000+ 3840X1600 Ultrawide monitor
>Uses it for Quake 2 and gets 40fps

Be glad you are not me.
"
It may not require a "nasa computer" but far more than a regular home pc as well. I don't know how the hell he get the 4k 90fps he mentioned.

**Comment by sycspysycspy** [comment]
Where is the guy who claimed that he could run the game at 4k 90fps with RTX on? Just a bluffing?

**Comment by gusmanb** [comment]
No bluff, just really busy. And I was wrong in something, it's 75-80fps, not 90, but more than enough.

![screenshot](https://user-images.githubusercontent.com/4086913/60904641-a7b35f80-a273-11e9-8814-75c53586170f.jpg)

**Comment by gusmanb** [comment]
> 
> 
> > > No, you will need a nasa computer to run it at full resolution for VR.
> > 
> > 
> > Not at all, I can run the RTX version at 4k 90fps, that's enough for two 1080x1200 screens.
> 
> What is your spec? I have a 1070, running the game with global illumination set to low, at 1600_900 50% resolution(800_450). Can not get a stable 60 fps. Maybe you have a 2080ti, but that is too expensive for most of the gamers.

I have a 2080 with a Rizen 7 2700xl and 16Gb DDR4 3333 btw. I just dropped my 1070 because it's pure crap for VR, I had the 1070 SuperOverclock of Gigabyte and it's not enough for VR. If you want a decent VR experience you need at least a 1080Ti.

**Comment by sycspysycspy** [comment]
Did you use downsampling to get that fps? Your screenshot looks blury(maybe due to compression, or the texture in the game itself is just like that). 
Here's someone's recording with a 2080ti, but he was playing with global illumination on high at 1440p. https://www.youtube.com/watch?v=YpdaiTKRzpM
I also learnt that there is some kind of reshade addon version of ray tracing which can be applied to many games. But sadly reshade doen't support VR yet, maybe that is a more general way to apply ray  tracing to unsupported games.
I think 1070 works fine for oculus rift, I had never encountered any performance issue with any vr title so far. I think geforce 2000s are over priced and RTX still need some performance boost to be practical. I am happy with the technology itself but I will have to wait.

**Comment by gusmanb** [comment]
Textures are blurry by themselves, they're the original ones on Quake II so it's not a surprise. I have the global illumination to low and sampling to 80%, global illumination does a big difference in performance but little to no difference in game quality as raytracing already makes it look gorgeous.

About 1070, I have the Oculus Rift and had tons of problems with games that run like crap: The forest, subnautica, Skyrim (with mods), the Solus project and a ton of Steam games that run really poorly.

Finally, about the boost, well, it depends on how the RTX tech is used. If you want a full raytraced game, yes, RTX is in it's early stages and only with the top of the RTX range you will be able to enjoy it, but games can opt to use raytracing only for shadows of reflections or illumination, like SotTR and Metro Exodus do, the impact is not as big as with a full raytraced game and the quality difference is really noticeable, for me the best are raytraced shadows, no more jaggy edges no matter how far the shadow is.

**Comment by gusmanb** [comment]
Just for curiosity I tested the exact same settings as that guy, 2560x1440 at maximum settings and I get nearly the same frame rate, only one or two frames of difference and my card is a 2080, not a Ti, and my CPU in single threading is a bit slower (but much faster in multithreading) so I assume that guy has something very badly configured as the 2080Ti should give a 15-20% nore frames, or the multithreading in RTX makes a big difference. I think I read somewhere that multithreading is very important for RTX so that may be the key for this.
